[package]
name = "high-level"
version = "0.0.0"
edition = "2021"

[dependencies]
lower-level = { path = "../lower-level" }
thiserror.workspace = true
log.workspace = true
serde.workspace = true
serde_json.workspace = true
http.workspace = true
hashbrown = { version = "0.14.0", features = ["serde"] }

[dev-dependencies]
tokio = { version = "1.29.1", features = ["full"] }