[package]
name = "high-level"
version = "0.0.0"
edition = "2021"

[dependencies]
lower-level = { path = "../lower-level" }
thiserror.workspace = true
log.workspace = true
serde.workspace = true
serde_json.workspace = true
http.workspace = true