[package]
name = "security-chat"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"

[profile.dev]
debug = 1
split-debuginfo = "unpacked"

[profile.release]
incremental = true

[workspace]
members = ["lower-level", "high-level", "crate-proto", "vim-like-command"]

[workspace.dependencies]
log = "0.4.19"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0.43"
http = "0.2.9"
tonic = { version = "0.9.2", features = ["gzip"] }
bincode = "1.3.3"

[dependencies]
tauri = { version = "1.4", features = [ "global-shortcut-all", "shell-open"] }
vim-like-command = { path = "vim-like-command" }
serde.workspace = true
serde_json.workspace = true
high-level = { path = "high-level" }
open = "5.0.0"
log.workspace = true
dirs = "5.0.1"
simple_logger = "4.2.0"
once_cell = "1.18.0"

[build-dependencies]
tauri-build = { version = "1.4", features = [] }

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
