disallowed-types = [
    { path = "std::collections::HashMap", reason = "HashMap in std is slow. Use HashMap from hashbrown" },
    { path = "std::collections::HashSet", reason = "HashSet in std is slow. Use HashSet from hashbrown" },
]