[package]
name = "crate-proto"
version = "0.0.0"
edition = "2021"
build = "build.rs"

[dependencies]
tonic.workspace = true
prost = "0.11.9"
prost-types = "0.11.9"

[build-dependencies]
tonic-build = "0.9.2"